### ISSUE TITLE
public override bool FindFirst(string tag) do nothing?

### ISSUE THREAD

**Issue by TruePluto** [kannan-ar/MariGold.HtmlParser#2]
I don't understand the function. Does it just return a bool determine that there is or not a specified tag in the html string? it doesn't return the tag note or change the current note to the specified tag that be found.

**Comment by kannan-ar** [comment]
Yes it does point the "Current" property to the first node of specified tag and return true if found or return false otherwise. Please see the code below.

```
HtmlParser parser = new HtmlTextParser("<div>test</div>");

if (parser.FindFirst("div"))
{
    string tag = parser.Current.Tag;
}  
```    
Let me know if you encounter a situation that the function fails.
